# Generated by Django 3.0.2 on 2020-05-22 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20200510_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.FriendshipStatus')),
                ('user_requested', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_requested', to=settings.AUTH_USER_MODEL)),
                ('user_requesting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
