# Generated by Django 3.0.2 on 2020-05-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200522_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshipstatus',
            options={'verbose_name_plural': 'friendship status'},
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='profile_requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_requested', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='profile_requesting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_requesting', to='profiles.Profile'),
        ),
    ]
