# Generated by Django 3.0.2 on 2020-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='friendshipstatus',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
