# Generated by Django 3.0.8 on 2020-07-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_manually_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshipstatus',
            options={'verbose_name_plural': 'friendship statuses'},
        ),
    ]
