# Generated by Django 3.0.9 on 2020-08-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_ingredient_notes'),
        ('profiles', '0010_auto_20200817_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipes_cooked',
            field=models.ManyToManyField(related_name='profile', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='only_host_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
