# Generated by Django 3.0.9 on 2020-08-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_ingredient_notes'),
        ('profiles', '0011_auto_20200824_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recipes_cooked',
            field=models.ManyToManyField(blank=True, related_name='profile', to='recipes.Recipe'),
        ),
    ]
