# Generated by Django 3.0.9 on 2020-08-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_ingredient_notes'),
        ('profiles', '0012_auto_20200824_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recipes_cooked',
        ),
        migrations.AddField(
            model_name='profile',
            name='recipes_cooked',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', through='profiles.RecipeCooked', to='recipes.Recipe'),
        ),
    ]
