# Generated by Django 3.0.10 on 2020-12-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_interaction'),
        ('profiles', '0014_auto_20200824_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interactions',
            field=models.ManyToManyField(blank=True, related_name='profile_2', through='recipes.Interaction', to='recipes.Recipe'),
        ),
    ]
