# Generated by Django 3.0.10 on 2020-12-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_interaction'),
        ('profiles', '0015_profile_interactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recipes_cooked',
        ),
        migrations.AlterField(
            model_name='profile',
            name='interactions',
            field=models.ManyToManyField(blank=True, related_name='profile', through='recipes.Interaction', to='recipes.Recipe'),
        ),
        migrations.DeleteModel(
            name='RecipeCooked',
        ),
    ]
