# Generated by Django 3.0.10 on 2021-01-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201008_2213'),
        ('profiles', '0016_auto_20201222_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forbidden_products',
            field=models.ManyToManyField(blank=True, related_name='profile', to='products.Product'),
        ),
    ]
