# Generated by Django 3.0.2 on 2020-05-10 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/%Y-%m-%d')),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='amount',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Weight'),
        ),
    ]
