# Generated by Django 3.0.2 on 2020-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200527_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y-%m-%d'),
        ),
    ]
