# Generated by Django 3.0.2 on 2020-06-02 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredient_substitutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='substitutions',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='recipes.Ingredient'),
        ),
    ]
