# Generated by Django 3.0.8 on 2020-08-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200806_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
