# Generated by Django 3.0.8 on 2020-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_ingredient_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
