# Generated by Django 3.0.9 on 2020-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_dishlabel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishlabel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
