# Generated by Django 3.0.10 on 2020-09-04 22:50

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20200901_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstructions',
            name='steps',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
