# Generated by Django 3.0.10 on 2020-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20200904_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeinstructions',
            options={'verbose_name_plural': 'recipe instructions'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, to='recipes.DishCategory'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='labels',
            field=models.ManyToManyField(blank=True, to='recipes.DishLabel'),
        ),
        migrations.AlterField(
            model_name='dishlabel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipes'),
        ),
    ]
