# Generated by Django 3.0.10 on 2020-12-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_interaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('profile', 'recipe'), name='unique_interaction'),
        ),
    ]
