# Generated by Django 3.0.11 on 2021-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20201222_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishlabel',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
