# Generated by Django 3.0.11 on 2021-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_auto_20210318_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishlabel',
            name='image',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
