# Generated by Django 3.0.11 on 2021-03-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_auto_20210318_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
