# Generated by Django 3.0.2 on 2020-03-24 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20200324_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='users.Profile')),
                ('groups', models.ManyToManyField(related_name='users', to='users.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertypes', models.ManyToManyField(related_name='users', to='users.UserType')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
