# Generated by Django 3.0.2 on 2020-03-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200324_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
        migrations.AddField(
            model_name='user',
            name='usertypes',
            field=models.ManyToManyField(related_name='users', to='users.UserType'),
        ),
    ]
