language: python

python:
  - "3.8"

env:


install:
  - pip install pipenv --upgrade
  - pipenv install --dev

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - cd src/
  - python manage.py migrate

scripts:
  - pipenv run lint --exit-zero
  - pipenv run pylint
  - pipenv run test
  - pipenv run cov-report

branches:
  only:
    - master
