# Generated by Django 3.0.10 on 2020-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
    ]
