# Generated by Django 3.0.11 on 2021-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20201031_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5)),
                ('rating_is_real', models.BooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
