# Generated by Django 3.0.8 on 2020-08-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_manually_fix'),
        ('inventories', '0003_auto_20200711_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_the_default_one', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='members'
        ),
        migrations.AddField(
            model_name='place',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='places', through='inventories.PlaceMember', to='profiles.Profile'),
        ),
    ]
