# Generated by Django 3.0.8 on 2020-08-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20200801_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='place',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventories.Place'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
