# Generated by Django 3.0.8 on 2020-08-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200722_2041'),
        ('inventories', '0005_auto_20200816_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='amount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Amount'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
    ]
