# Generated by Django 3.0.9 on 2020-08-26 19:28

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_amount'),
        ('inventories', '0007_auto_20200826_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Unit'),
        ),
    ]
