# Generated by Django 3.0.9 on 2020-08-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_auto_20200826_1928'),
        ('inventories', '0007_purchase_purchaseitem'),
    ]

    operations = [
    ]
