# Generated by Django 3.0.9 on 2020-08-27 18:01

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200827_1801'),
        ('inventories', '0009_merge_20200827_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Unit'),
        ),
    ]
