# Generated by Django 3.0.9 on 2020-08-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_auto_20200827_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
    ]
