# Generated by Django 3.0.7 on 2020-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='short_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
