# Generated by Django 3.0.9 on 2020-08-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200722_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='unit',
        ),
    ]
