# Generated by Django 3.0.9 on 2020-08-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_amount_unit'),
        ('inventories', '0007_auto_20200826_1847'),
        ('recipes', '0016_auto_20200826_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
