# Generated by Django 3.0.9 on 2020-08-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200826_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avg_weight',
            new_name='avg_unit_weight',
        ),
    ]
