# Generated by Django 3.0.9 on 2020-08-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200827_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_dimensionalities',
            field=models.CharField(default='[unit]', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='avg_unit_volume',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='dimensionality',
            field=models.CharField(default='[unit]', max_length=50),
        ),
    ]
